"""
Standalone Strategy Base Class

Each strategy is an independent async coroutine that:
- Subscribes to Redis price streams
- Generates trading signals
- Publishes signals to its own signal stream
"""

import asyncio
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    action: str  # 'buy', 'sell', 'close'
    price: float
    reason: str
    size: float
    strategy: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "price": self.price,
            "reason": self.reason,
            "size": self.size,
            "strategy": self.strategy,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


class StandaloneStrategy(ABC):
    """Base class for all standalone strategy coroutines.

    Each strategy:
    - Subscribes to Redis streams it needs (prices, regime)
    - Tracks its own position state
    - Generates signals independently
    - Publishes signals to its own stream
    """

    def __init__(self, redis_client, config):
        """
        Args:
            redis_client: RedisClient instance for stream operations
            config: Strategy configuration
        """
        self.redis = redis_client
        self.config = config
        self.position = None  # Each strategy tracks its own position
        self.running = True
        self.logger = logging.getLogger(f"strategy.{self.name}")

        # Position tracking
        self._in_position = False
        self._entry_price = 0.0
        self._entry_time = None
        self._position_size = 0.0

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy identifier (e.g., 'v35', 'short_v1')"""
        pass

    @property
    @abstractmethod
    def exchange(self) -> str:
        """Exchange this strategy trades on ('upbit' or 'binance')"""
        pass

    @property
    @abstractmethod
    def subscribed_streams(self) -> List[str]:
        """Streams this strategy needs (e.g., ['market:upbit:prices'])"""
        pass

    @abstractmethod
    async def on_price(self, price_data: dict) -> Optional[Signal]:
        """Process price update, return signal if any.

        Args:
            price_data: Dict with price, volume, timestamp, etc.

        Returns:
            Signal if action needed, None otherwise
        """
        pass

    async def on_regime(self, regime_data: dict) -> None:
        """Process regime update (optional override).

        Default: store for reference, no action.
        """
        self._current_regime = regime_data.get("regime")
        self._current_market_state = regime_data.get("market_state")

    def enter_position(self, price: float, size: float):
        """Record position entry"""
        self._in_position = True
        self._entry_price = price
        self._entry_time = datetime.now()
        self._position_size = size
        self.logger.info(f"Entered position: price={price}, size={size}")

    def exit_position(self):
        """Record position exit"""
        self._in_position = False
        self._entry_price = 0.0
        self._entry_time = None
        self._position_size = 0.0
        self.logger.info("Exited position")

    @property
    def in_position(self) -> bool:
        return self._in_position

    @property
    def entry_price(self) -> float:
        return self._entry_price

    async def run(self):
        """Main loop - subscribe and process messages."""
        self.logger.info(f"Starting {self.name} strategy...")

        # Create consumer group for this strategy
        group_name = f"strategy:{self.name}"
        for stream in self.subscribed_streams:
            await self.redis.create_consumer_group(stream, group_name, start_id="$")

        while self.running:
            try:
                # Consume from all subscribed streams
                messages = await self.redis.consume(
                    stream_name=self.subscribed_streams[0],  # Primary stream
                    group_name=group_name,
                    consumer_name=self.name,
                    count=10,
                    block=1000,
                )

                for msg in messages:
                    stream = msg.get("stream", "")
                    data = msg.get("data", {})

                    # Route to appropriate handler
                    if "prices" in stream:
                        signal = await self.on_price(data)
                        if signal:
                            await self._publish_signal(signal)
                    elif "regime" in stream:
                        await self.on_regime(data)

                    # ACK the message
                    await self.redis.ack(stream, group_name, msg["id"])

            except asyncio.CancelledError:
                self.logger.info(f"{self.name} strategy cancelled")
                break
            except Exception as e:
                self.logger.error(f"Error in {self.name}: {e}", exc_info=True)
                await asyncio.sleep(1)  # Brief pause before retry

        self.logger.info(f"{self.name} strategy stopped")

    async def _publish_signal(self, signal: Signal):
        """Publish signal to this strategy's signal stream."""
        stream_name = f"signals:{self.name}"
        await self.redis.publish(stream_name, signal.to_dict())
        self.logger.info(f"Published signal: {signal.action} @ {signal.price} ({signal.reason})")

    def stop(self):
        """Stop the strategy gracefully."""
        self.running = False
